#################################################
# Application
#################################################

spring.application.name=Employee Task Manager


#################################################
# Database Configuration
#################################################

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/myfirstdb}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:Sai@14052005}


#################################################
# JPA / Hibernate
#################################################

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


#################################################
# Actuator
#################################################

management.endpoints.web.exposure.include=*
management.info.env.enabled=true


#################################################
# Application Info
#################################################

info.app.name=Employee Task Manager
info.app.version=1.0
info.app.description=Task Management REST API using Spring Boot
info.app.author=Sai Kumar